language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- gem install bundler
- bundle install
- npm install
- npm install -g bower
- npm install -g grunt-cli
- bower install
- grunt deploy:production
- exit 0
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: WSgbbMecVDaU9+J1KBESHf32FW+hDuRR69dpdehBov4zI4H+4UnwEbgvkfsRo9E88uAlLPY4weiGAWycyg6t4f5zn/QQQceRUtgUTuAyj6hvpbmN3la2DXGJsmyZrSMNXIacmvFXHuIpGjAAevgNs7eC5l5nPXFy+ZHZWldKCDMKdWH5Zw0h/j7rLDmQehJlIcbPKTK1B5NfWgnVd2QY2uyN7Fht/cuf2UMy7Nys2aBCCkFGC9rNhDUDOY9jRRxhDzMVf6hHPRejIn4IKkhV9aYVUT1xoQPLv8uePVm0WfU3PiZvbhLsTrjABUnVNfFQE0mwo62frq3CEfNUD6keE1lfCPKNMgQ6Gsu+s41IM9z99wmz6V9Ww2fjm/fpvbqkwbWP2YDp7gRAY2sIQdB0gaDj6zxiHXyMu/6181nVcTVEzsd5nYTU/N6TeZA7pDHsgQBVZp5pzlHWL66nR7xUX/++MpyNleHaEXOEuVSg5nm6xDMbQtyE5l+XM1utG4erZ3Hdbz1VxwbZxfPthDGavBzEaIk1d7keewXxxe2gvDseeJbMs4wGco3ZV57Zos2iJta/PippPxnh1yr8A7VyiNj10LdY7qqWgksXrfNdD7743n+SwP2QXQot3RPUljr5Ihs9ycc6JJx9n+QoKWW7hDQkpNzN48M2utX9Fuhx01A=
  - secure: ewAgm/3W+twA5QYwxS6vv1jAaqT6VqrEtIxSiAoQAbRLLHyhZK8juPjffwlMrnkT2Xrs0bHWmc1gqr8YBQJtJ77kB+SZhk7o2mz3zdfrnHQSHAspVc5bOwm/kKcdNaeVuw4U6vriTMx0pPPq7OqRfT1Q1OD7EzaGNLD6SZwn5TKVZFJZpnV4KROXuZWKiOd/oQtY3nHhk2S5K2MBZSYQ92+GwzZ5DH7lE5V5UGTX+dhtMWYRt3bZfj7dp0o7OS5GfjliFIKTRGyiJPeaeUc8/aZvUIOejeMfb/7zLKl80RJO+OJOdGZIskn1Tz9kY2Gkx3lMN1sxugRUfc7MnkrDE2zgKtPQS/5IHKM7gyW83pzJtLZT6Qc2bl99oulcxK6YVQ6NzmZOGdokPn4kqXxZD91ZprIxJI1i9fBZvlXBa3wKAFgrI7GyUMPzWE/RpZKoUKZT4Za+9oEmTh1IeRiodFeqLI1ieQBo2eXbbgjf4MF6aV9leLizgml0ekiCT3mJm9U5/f6b5St2xf32okggeoZvj14bSyyHhx5DEKPtz4BjQgB5rRzbHuprIZZCpAKrCpc+vQyXLrgkz/Gn6+oG0ny6l9oam6v9bIrVR69lPnn1j12uu5sAHxots53lwllvSzzJRethFELWtyYamoAMU9dHWK/UlRJ9Fsh3Le6X1u8=
