language: javascript
install: 
 - gem install bundler
 - bundle install
 - npm install
 - npm install -g bower
 - npm install -g grunt-cli
 - bower install
 - grunt devBuild
notifications:
 on_success: never
 on_failure: always