language: node_js
node_js:
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- gem install bundler
- bundle install
- npm install
- npm install -g bower
- npm install -g grunt-cli
- bower install
- grunt deploy:production
- echo \$app_url = \"http:\/\/$PROD_TC_URL:8080\/med-checker\" > test/selenium-ruby/spec/_config.rb
- sleep 10
- grunt selenium
- exit 0
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
  - secure: VNRd652+VjdESkOjcV0b3zdRKO6BDQqe6gvhRcZCwyJsbytbFuHydnfbdObBuUoBxrMUkbViE7jV/DMY5He+JQCzK2tBJq4h/6xwreC49D1xPRzlVv8ALGZ78LtQJSpzR1mmEMsP1mFEVdgwhhD9ILWx7iQOJnYLkYagyNKcM3y0ueKu9CiMvDPtuousRzJ2yRaxGsI+BBULqgtHHoEOhAJYOpYaqDlBdmEDG1hYMO1+SD3laNdm36iZTgd8Zv/XNlUq0H6RUs2TKieifWpReLe3Xcg/v3EfbMbfjpU7gfAGzFXcRNCRKuiy58WZGrI4zCRkaWRP2WsiIUg/xWWAt+/MKwC6eXez8RO6OlVbNH2Azj3Z0duHdezJHZYttTP/B+CS/jTi2j2J04o3GCfgpHbvaG4vkf8YsLWTid6xMe465gxw/CnY/xPpKOWJkEWqgRsjMJZy254Vg+lxdJgZZKf6ioEolHeOPrqVnbbVCBFFT7saCwVhCLkFHVkNj40bZLQ+6n4ge/WeZ2hb4HId1piOZtTn/XDtFz7QToV2WugKeyy/wFoKs+MZdL9L7iFQFG8WDZOWv7gQz05iieFMRtB0+PVEiVEUW4zqNz8xwZ09RYcsMi3AWV41qaiNducMaSbeNtMh1DG0SSMRjRfO+jK+dOT6p/DlAgRIYStZJ3U=
  - secure: IWpCYLA7pL1IrSIwwSLyHMw/Vrw5qSGSmWmHiolnrkRNBeFacITZ+hWD00ZimIIWJwSLWJZVZUnP5hhLJHHOU9FqBkju1QXOjG6aFUOlI/jAC0mnbp9f7UqL8D8dLc2FlMchf0TGIqIUcU/1Cdf+TOoRgPSf9L/Weyonta2Dym5kEz+JZoaJbpsPMOe/gmAnJNa5KC5J3FH9T0cyNfwhScGFHr+G8HwnQiH0DlSBBgo0cXx58heRqyN0TJvfG8hlx2ss1+RanPMH8WZ/2Rv3TRNh2vnZcnusv6G2B97LCkfbS4G/B/IdIWRNTllCM7OOIL6UT6eYOUAGfXJEqbsP2x7d8DlD8LLoIF6+u81E7o5bJ7deHKDQrIiJWxHfyuOd1CC+BEZZu3K0pCHXTHcAnDhLYdl94FkSog+e3T+8nmt726zILJGX++WWQG9Apt0omRbMSwjNIcXaUOHrc0mI6QR53x/HK0xyYB7jJGvBhVEmz8jc8rOGZRBLCMPwC1fFGmCDEfGpV65Zh1TQBgdkSKBkbX9ZyRC2gUQ7Dcwz674uZTI3pyhV2+YerSAnWxMIH8G6NF1j+EG/B8ouP6W5bSjHox61/S0cixfFQA0rfxMNtsU37p+S1LEBqaNILhdXpD291gwajSXuqdChSILQHckATxFrAP9dUgJRTBlHydg=
